### ISSUE TITLE
Put Repos path information in configuration file

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/bigbang#129]
Related to #113 the path of the save Git repos is currently hard-coded in many places in the code. At the time of this writing, it looks like there's a bug in git repo loading in the notebook because these paths are out of sync.

**Comment by Aryan-Barbarian** [comment]
I'll get to work on this as part of a larger clean-up effort. A lot of the git things I programmed were on the spot and janky, so I should definitely make them more official.

**Comment by Aryan-Barbarian** [comment]
@sbenthall : wondering if you had any suggestions on how to handle the logic of a configuration file! I've made a few for personal projects before, but I'm not really sure if there are any "best practices"

**Comment by Aryan-Barbarian** [comment]
@sbenthall, I was wondering what format I should use (yaml, json, xml, etc.)

**Comment by sbenthall** [comment]
Sorry--I see now I left your earlier comment hanging.

Let's use YAML. XML and JSON are both 'human readable' but require extra syntax that makes them harder to edit.
