### ISSUE TITLE
Create git interaction graph based on Git commit network

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/bigbang#136]
In an IPython notebook, transform the Git commit network from #135 into a network of interaction and collaboration between commit authors.

In this graph, nodes are commit authors, with metadata for total number of commits. Edges are weighted as the number of times an author made a commit immediately downstream of another's commit (whether this is a branch or a merge). Edges with weight 0 are not included in the graph.

Visualize this network in the notebook.

**Comment by Aryan-Barbarian** [comment]
Would it be a good idea to create a class for File, Author, Commit? We don't really *need* it, but I was just wondering about it in case there's a sort of "best practice" for this sort of thing.

**Comment by sbenthall** [comment]
That's a good question, Aryan. The danger I see in making separate classes for File, Author, and Commit is that might replicated functionality of the lower level libraries that parse the Git repos.

On the other hand, if there was some additional information we were integrating into BigBang's internal notion of File, Author, and Commit (for example, if our Author objects also included data about what emails that person had sent) I could see how there would be a lot of value added to this.

This raises deep questions about our data model, storage, and how our code interacts with it. I don't have a ready answer about this right now but it's a great question and one we should definitely look into more.

**Comment by sbenthall** [comment]
Closing this as fixed since #141 Thanks Ven!
