### ISSUE TITLE
Add parents and diff data to GitRepo dataframe

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/bigbang#137]
The Pandas dataframe wrapped by GitRepo does not yet have in it two kinds of data about the commits:
 * information about which commit each commit is a descendant of in the network. It might be the descendant of more than one commit if it is a 'merge' commit, for example.
 * the information about the 'diff' of each commit.

Add this data to the GitRepo dataframe.

**Comment by Aryan-Barbarian** [comment]
So I just made a pull request (in progress) that adds parent information. However, I don't have the diff information yet. The library I'm using for git information has some extra diff features which could be cool. This is some more info. Hopefully I'll have this by the end of the week.

More info in case you are interested: http://gitpython.readthedocs.org/en/stable/tutorial.html#obtaining-diff-information.

**Comment by sbenthall** [comment]
Thanks for the pull request! That should be directly useful for #135 

I see. I guess what I was thinking when I posted this ticket was adding a diff against the index as a column for each commit. But maybe that wasn't super thought through.

There are a lot of ways we could do this, including using diff content (line by line) and just looking at which **files** were touched in a commit. While I was thinking the former, the latter could be a lot of straightforward for a first pass.

A next step, along the lines of #135 and #136 is to do a network visualization with three kinds of nodes: authors, commits, and the files that they touch in the file system.

Looping in @vsporeddy onto this ticket.

**Comment by Aryan-Barbarian** [comment]
I just figured out how to get any type of diff we would like.

This including line-by-line diffs, as well as general statements such as files being created, deleted, modified, etc.

I'm going to think about how to make our git program let the user decide which part of this information they'd find useful. Getting the line-by-line is supposedly a little more costly since we have to open each blob and diff it.

**Comment by Aryan-Barbarian** [comment]
I just sent a pull request #139 for diff information. I discussed some performance issues with it there too.
