### ISSUE TITLE
Unexpected network structure in Git Diffs notebook

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/bigbang#140]
I've done some digging into the network generated by the Git Diffs notebook. I think there is a bug somewhere in the code.

To look at the network in closer detail, I first added this line to the notebook in order to export the data:

    nx.write_gexf(G,'bigbang-diffs.gexf')

Then I opened the file that creates, bigbang-diffs.gexf, in Gephi: http://gephi.github.io/

Below is the network data with edges sized by degree. I separated out the authors from the file names by hand (in the future we'll want to automate this):

![git-diff-graph](https://cloud.githubusercontent.com/assets/68752/6315351/0da52c54-b9b4-11e4-9d3e-ab2c5f874208.png)

As you can see, according to this, every committer has touched almost every file. I think the graph should look different, since many of the committers have to my knowledge only ever touched one or two files. What's happening here?

**Comment by sbenthall** [comment]
looping in @vsporeddy

**Comment by Aryan-Barbarian** [comment]
I suspect that I'm doing something wrong with how GitPython does commits. I'll check it out. Also thanks for showing me this tool, I didn't know about this visualization tool before!

**Comment by Aryan-Barbarian** [comment]
I think I figured out the bug! GitPython does diffs between two different commits. In my previous code, each commit's diff was calculated based on its difference with the HEAD commit. Now, the diff is calculated from that commit's first parent.

There's still a lot of bugs, but I put a pull request so you can look at the code. #142.

**Comment by Aryan-Barbarian** [comment]
By the way, keep in mind that there are still commits that seem like they touched a lot of random files, but this isn't errant behavior. For example, my commit bdc9e64307b2c6312491729053fa9d4ac0ece74f was a merge commit that edited 10 random files.

**Comment by sbenthall** [comment]
Awesome! Thanks for this fix.
