### ISSUE TITLE
In Git Diff notebook, weight edges by number of times an author touched a file

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/bigbang#144]
Inspired by some of the comments on #140, it would be good if the network created by Git Diff had weighted edges, where an edge between an author and a file was equal to the number of commits they have made that touch the file. 

Here is an example of how to do weighted edges:

http://networkx.github.io/documentation/networkx-1.9/examples/drawing/weighted_graph.html

cc @Aryan-Barbarian @vsporeddy

**Comment by Aryan-Barbarian** [comment]
I was thinking of implementing this as an adjacency matrix, rows being authors and columns being files. 

The value for each cell at row AUTHOR and column FILE would be how many times that AUTHOR modified that FILE.

It's the best way to do this for now, but it could limit future functionality (looking at this over time, for example.)

**Comment by sbenthall** [comment]
Closed with #152 Thanks Ven!
