### ISSUE TITLE
Example Notebook Analyse Sender -> function called which is not defined

### ISSUE THREAD

**Issue by nllz** [sbenthall/bigbang#240]
In the example AnalyseSender.ipynb on code line 110 this is called:
    "activities = [process.activity(ml) for ml in mlists]"
but activity is not defined in process.py. This makes the example to malfunction. I assume that activity is supposed to count the total of all emails sent, but am not sure, and not yet well versed in the panda data frame. Happy to contribute and discuss.

**Comment by sbenthall** [comment]
Did changes #241 and #242 fix this problem?

**Comment by nllz** [comment]
Yes!
